### ISSUE TITLE
Review revisit record's warc header

### ISSUE THREAD

**Issue by MohammedElsayyed** [arcalex/warcrefs#15]
The following is a code snippet of how Deduplicator class writes warc header for each revisit record:

```java
        warcHeader.header.warcTypeStr = "revisit";
        warcHeader.header.warcTargetUriStr = record.header.warcTargetUriStr;
        warcHeader.header.warcDate = record.header.warcDate;
        warcHeader.header.warcPayloadDigest = record.header.warcPayloadDigest;
        warcHeader.header.warcIpAddress = record.header.warcIpAddress;
        warcHeader.header.warcProfileStr
                = "http://netpreserve.org/warc/1.0/revisit/identical-payload-digest";
        warcHeader.header.warcRefersToTargetUriStr = refersToUri;
        warcHeader.header.warcRefersToDateStr = refersToDate;
        warcHeader.header.warcRecordIdUri = record.header.warcRecordIdUri;
        warcHeader.header.contentType = record.header.contentType;
        warcHeader.header.contentLength = ( long ) httpHeaderStr.length(); 
```

As shown above, Deduplicator changes warcType to 'revisit' instead of 'response' and recalculates the content length. It also adds new attributes, namely, warcProfile (fixed string), warcRefersToTargetUri, and warcRefersToDate. It copies the rest of the attributes as they are from the original record.

@youssefeldakar Can you confirm it please?

**Comment by youssefeldakar** [comment]
I do not see something in particular that would be incorrect in what was described.

**Comment by MohammedElsayyed** [comment]
After discussing this issue with @youssefeldakar, the following points are worth taking them into consideration:

1. The new WARC revisit record's fields should be consistent in terms of datatype.
2. If it is not possible to apply the previous rule on all fields, then it should be applied at least on fileds with the same context (e.g. date fields 'warcDate' and 'warcRefersToDate').

**Comment by MohammedElsayyed** [comment]
To close this issue, my humble opinion is doing the following:

```java
warcHeader.header.warcDateStr = record.header.warcDateStr;
warcHeader.header.warcRefersToDateStr = refersToDateStr;
```

is better than the following:
```java
Date refersToDate = new Date( refersToDateStr );
warcHeader.header.warcDate = record.header.warcDate;
warcHeader.header.warcRefersToDate = refersToDate;
```

Because there is no need in terms of performance to create a new Date object especially they will give us the same result. In addition to, Date constructor with a String parameter is depricated.

**Comment by MohammedElsayyed** [comment]
The same for 'warcTargetUri' and 'warcRefersToTargetUri'.

**Comment by MohammedElsayyed** [comment]
The following is a sample of WARC revisit record:

WARC/1.0
WARC-Type: revisit
WARC-Record-ID: <urn:uuid:3a2612a9-f716-40ce-b675-6adab7bcfb6a>
WARC-Date: 2011-07-31T05:05:44Z
Content-Length: 359
Content-Type: application/http; msgtype=response
WARC-Payload-Digest: sha1:26LQJ3XCUG7EQ64EWJYOPXLCJ65S2JWG
WARC-IP-Address: 195.238.240.112
WARC-Target-URI: http://blogs.reuters.com/fullfocus/files/2011/02/24GoranLibyaFullFocus.jpg
WARC-Profile: http://netpreserve.org/warc/1.0/revisit/identical-payload-digest
WARC-Refers-To-Target-URI: http://community.nytimes.com/comments/formulaone.blogs.nytimes.com/2010/02/28/mario-andretti-turns-70-goes-to-bahrain/
WARC-Refers-To-Date: 2011-07-31T05:05:45Z

@youssefeldakar in line #6 there is a 'msgtype=response'. Should it be changed to revisit?

The following is a sample of HTTP header:

HTTP/1.1 200 OK
Date: Sun, 31 Jul 2011 05:05:44 GMT
Server: Apache/2.2.3 (CentOS)
Last-Modified: Sat, 23 Apr 2011 13:17:46 GMT
ETag: "37d807d-32096-4a195ccdbd280"
Accept-Ranges: bytes
Content-Length: 204950
X-Cachetype: Cached-with-imagecache
Vary: Accept-Encoding,Cookie
Cache-Control: max-age=300, must-revalidate
Connection: close
Content-Type: image/jpeg

**Comment by youssefeldakar** [comment]
The content type is not going to change for a revisit record. 'response' in 'msgtype=response' is in the context of HTTP, not WARC. We are good.
